name: Compare Hashes

on:
    push:
        branches: [ main ]

jobs:
    compare-hashes:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                file: [dbplyr-NEWS-old.md, dplyr-NEWS.md]
                url: [https://raw.githubusercontent.com/tidyverse/dbplyr/main/NEWS.md, https://raw.githubusercontent.com/tidyverse/dplyr/main/NEWS.md]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Get local file hash
              id: local-hash
              run: echo "::set-output name=hash::$(md5sum ${{ matrix.file }} | cut -d ' ' -f 1)"
            - name: Get remote file hash
              id: remote-hash
              run: echo "::set-output name=hash::$(curl -s ${{ matrix.url }} | md5sum | cut -d ' ' -f 1)"
            - name: Compare hashes
              run: |
                    if [ "${{ steps.local-hash.outputs.hash }}" = "${{ steps.remote-hash.outputs.hash }}" ]; then
                        echo "Hashes match!"
                    else
                        echo "Hashes do not match!"
                        
              